// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzX5OVCOAewu1dykp8mpA-sNU7mDZ4My8',
    appId: '1:59317416635:web:18e4f2cc86b3b557b5ef9e',
    messagingSenderId: '59317416635',
    projectId: 'gdg-test-adda8',
    authDomain: 'gdg-test-adda8.firebaseapp.com',
    storageBucket: 'gdg-test-adda8.firebasestorage.app',
    measurementId: 'G-LNB590GMKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFjjBQKUSwXE3UxAfJbO11R2wYvyCQOq8',
    appId: '1:59317416635:android:e80a346e477e7797b5ef9e',
    messagingSenderId: '59317416635',
    projectId: 'gdg-test-adda8',
    storageBucket: 'gdg-test-adda8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB4YuKQ4Aq1F0NyuUcKPS_oTv4E8AhTsQ',
    appId: '1:59317416635:ios:2956c8f8c9b976e5b5ef9e',
    messagingSenderId: '59317416635',
    projectId: 'gdg-test-adda8',
    storageBucket: 'gdg-test-adda8.firebasestorage.app',
    iosBundleId: 'com.example.promotional',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB4YuKQ4Aq1F0NyuUcKPS_oTv4E8AhTsQ',
    appId: '1:59317416635:ios:2956c8f8c9b976e5b5ef9e',
    messagingSenderId: '59317416635',
    projectId: 'gdg-test-adda8',
    storageBucket: 'gdg-test-adda8.firebasestorage.app',
    iosBundleId: 'com.example.promotional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzX5OVCOAewu1dykp8mpA-sNU7mDZ4My8',
    appId: '1:59317416635:web:e695b1ccd179bb6db5ef9e',
    messagingSenderId: '59317416635',
    projectId: 'gdg-test-adda8',
    authDomain: 'gdg-test-adda8.firebaseapp.com',
    storageBucket: 'gdg-test-adda8.firebasestorage.app',
    measurementId: 'G-2GCG4MZB6C',
  );
}
